### ISSUE TITLE
Anzahl der abgegebenen Stimmen bei dem Attribut Bewertung.

### ISSUE THREAD

**Issue by CrawlingKing** [MetaModels/attribute_rating#1]
Hi,
es wäre toll, wenn man bei dem Attribut Bewertung die Anzahl der abgegebenen Stimmen anzeigen lassen könnte. Des Weiteren wäre es super, wenn auch die Sortierfunktion die Anzahl der abgegebenen Stimmen berücksichtigen würde.

Lg Michael

**Comment by Schnubl** [comment]
Also ich verwende das Rating Attribut zur Bewertung eines Eintrags, somit reicht mir eine Sortierung nach Anzahl der Stimmen, ich würde aber gerne auch die Anzahl anzeigen, ist dies irgendwie möglich?

**Comment by discordier** [comment]
@Schnubl im rating template:
```php
<?= $this->raw['votecount'] ?>

**Comment by Schnubl** [comment]
yeah, danke xtra!! ;)
