### ISSUE TITLE
Keine Images/Sterne, nur Radio-Buttons

### ISSUE THREAD

**Issue by engineoliver** [MetaModels/attribute_rating#10]
Bei mir werden im Front- und Backend anstatt der im Attribute-Konfig ausgewählten Bilddateien (leer, voll, hover) nur simple Radio-Buttons angezeigt.

Im Seitenlayout sind alle MooTools aktiviert.
Im Contao Root-Verzeichnis befinden sich SimpleAjax.php und SimpleAjaxFrontend.php.

Hat jemand eine Idee, wodran es liegt? Vielen Dank!

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@engineoliver could you please have a final look at this and tell if your issue has been resolved?
