### ISSUE TITLE
Rating Attribute geht derzeit nicht?

### ISSUE THREAD

**Issue by reneaye** [MetaModels/attribute_rating#15]
Das Rating Attribute geht derzeit nicht, oder? Es wird bei mir keine Tabelle in der Datenbank angelegt. In der Backend-Listenansicht wird noch etwas angezeigt, aber wenn ich ein MM editieren will, bekomme ich eine Fehlermeldung.

habe das 2.0.0 bundle_all installiert

**Comment by MacKP** [comment]
Das reting Attribute darf auf keine Fall im Backend ausgegeben werden!
Ist nur für das Frontend geeignet. Wenn du das berücksichtigst, dann solltest du schon mal keine Fehlermeldung bekommen ;-)

Viele Grüße

**Comment by reneaye** [comment]
Aber ich muss doch in der BE Liste in meinem MetaModel Eintrag (wie ist hier das richtige Wording?) die Anzahl der Sterne einstellen können. Weiterhin: sobald ich das Attribut angelegt habe, muss doch auch gleich ein entsprechendes Feld in der  Datenbank-Tabelle erzeugt werden, z.B. mm_bewertung (je nachdem, was ich in den Attribut-Einstellungen eingetragen habe). Da kommt aber keins.

**Comment by MacKP** [comment]
In der Liste musst du nichts einstellen. Dadurch bekommst du die Fehler. Ich weiß jetzt nicht was für eine Tabelle gesetzt wird, wenn man das Attribut installiert. Das sollte aber schon geschehen, bevor du das Attribut überhaupt einstellst. Das ist ein reines Frontend Attribut und darf auf keine Fall im Backend ausgegeben werden, wie ich schon geschrieben habe. 
Also: gib das Attribut nur im Frontend aus und Probiere es aus. Wenn du dann noch Probleme hast, dann melde dich bitte erst mal im Forum. bisher kann ich keine Grund für ein Ticket feststellen und schließe das erst mal.

Viele Grüße
