### ISSUE TITLE
Can not install while require for leounglaub/contao-simple-ajax failed 

### ISSUE THREAD

**Issue by baumannsven** [MetaModels/attribute_rating#18]
This package require leounglaub/contao-simple-ajax in version 1.0.
The version 1.0 is removed from leounglaub/contao-simple-ajax.

This package must be used leounglaub/contao-simple-ajax ~2.0.

**Comment by zonky2** [comment]
we can fix the json to version 2.0 of simple-ajax or change to the version of @richardhj https://github.com/richardhj/contao-simple-ajax

**Comment by discordier** [comment]
We should discuss this.

**Comment by zonky2** [comment]
add at JSON

```
    "require": {
...
        "leounglaub/contao-simple-ajax": "2.0.0 as 1.0.0",
...
    },
```

**Comment by zonky2** [comment]
we chance to... https://github.com/MetaModels/attribute_levensthein/pull/2#issuecomment-304986212

[MM-call 30.05.2017]

**Comment by zonky2** [comment]
it´s fixed with https://github.com/MetaModels/attribute_rating/pulls
