### ISSUE TITLE
Sortierung berücksichtigt nur Anzahl der Sterne nicht aber die Anzahl der Votes

### ISSUE THREAD

**Issue by Schnubl** [MetaModels/attribute_rating#23]
## My environment is:

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:  | 7                    
| Contao version:  |   3.5.35               
| MetaModels core version:  |   2.0.2           
| Installation via composer:          | (yes) 
| Installed MetaModels packages:  |metamodels/attribute_rating 2.0.5; metamodels/bundle_all  2.0.0
| DCG version: | contao-community-alliance/dc-general  2.0.0-beta47

## Issue description
Derzeit wird nur die Anzahl der gevoteten Sterne bei der sortierten Ausgabe nach Bewertung berücksichtigt, führt zu unschönen Listenausgaben wenn viele Einträge die gleiche Anzahl an Sternen haben, da ein Eintrag mit 5 Sternen aber 200 Votes mehr gewicht haben soll als ein Eintrag mit 5 Sternen aber nur 4 Votes.

netzmacht hat mir im IRC bereits einen lösungsvorschlag gepostet, leider hat dieser nicht richtig funktioniert, es wird zwar teilweise richtig sortiert aber zwischendrin kommt doch wieder ein falscher Eintrag vor.

> [10:28] <netzmacht> wenn du zeile 432 entsprechend mit ".$strDirection . ', votecount ' .$strDirection," ersetzt, sollte das gewünschte verhalten da sein

Vielleicht könnte ihr das Verhalten bei einem nächsten Update einbauen/korrigieren?

Danke

**Comment by zonky2** [comment]
@Schnubl 
dann setz Dich bitte mal an Dein phpMyAdmin und erstelle ein SQL-Query, was Deine Anforderung abdeckt - dann kann man das hier (https://github.com/MetaModels/attribute_rating/blob/master/src/MetaModels/Attribute/Rating/Rating.php#L430-L433) umsetzen

**Comment by Schnubl** [comment]
Wenn ich das könnte hätt ichs bereits getan :)

Sorry aber dafür reichen meine Kentnisse bei weitem nicht, darum hab ich ja das Ticket erstellt, ich hab mich auch gefragt warum das bisher noch keinem aufgefallen ist.

**Comment by zonky2** [comment]
> ..ich hab mich auch gefragt warum das bisher noch keinem aufgefallen ist.

Vielleicht, weil es - wie im Wiki zu sehen - nicht so trivial ist, die "richtige" Sortierung zu gestalten... das ist durchaus individuell

**Comment by Schnubl** [comment]
ok dann werd i im forum mal fragen ob sich das jemand anschauen kann, vielleicht hat ja netzmacht noch ne idee.

**Comment by zonky2** [comment]
in MM 2.2 gefixt
