### ISSUE TITLE
Rating sollte gesperrt werden, wenn Stimme abgegeben ist

### ISSUE THREAD

**Issue by MacKP** [MetaModels/attribute_rating#7]
An sich wird man ja für 24 Stunden gesperrt. Die Sperre ist auch schon aktiv, nachdem man abgestimmt hat, leider sieht man das nicht. Es sieht immer noch so aus, als ob man abstimmen kann, bis man die Seite neu geladen hat.

**Comment by zonky2** [comment]
gefixt in MM 2.2
